# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('area_map_image', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('area_map_imagemap_snippet', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('?', '?'), ('3', '3'), ('3+', '3+'), ('4', '4'), ('4+', '4+'), ('5', '5'), ('5+', '5+'), ('6A', '6A'), ('6A+', '6A+'), ('6B', '6B'), ('6B+', '6B+'), ('6C', '6C'), ('6C+', '6C+'), ('7A', '7A'), ('7A+', '7A+'), ('7B', '7B'), ('7B+', '7B+'), ('7C', '7C'), ('7C+', '7C+')], default='?', max_length=50)),
                ('steepness', models.CharField(blank=True, choices=[('slab', 'slab'), ('vert', 'vertical'), ('slov', 'slight overhang'), ('over', 'overhang'), ('exov', 'extreme overhang'), ('na', 'not applicable')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture_1', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('picture_2', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('picture_3', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('video_snippets', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('exists', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtificialProblem',
            fields=[
                ('baseproblem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BaseProblem')),
                ('date', models.DateField(blank=True, null=True)),
                ('holds', models.CharField(blank=True, max_length=300, null=True)),
                ('setter', models.CharField(blank=True, max_length=300, null=True)),
            ],
            bases=('guide.baseproblem',),
        ),
        migrations.CreateModel(
            name='NaturalProblem',
            fields=[
                ('baseproblem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BaseProblem')),
                ('rock_type', models.CharField(blank=True, max_length=50, null=True)),
                ('first_ascensionist', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('guide.baseproblem',),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Area'),
        ),
    ]
