# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemvideo',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='problemvideo',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
        migrations.AddField(
            model_name='problemimage',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
        migrations.AddField(
            model_name='problembymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='problembymember',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Area'),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_problem_set', to='members.Member'),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Sector'),
        ),
    ]
