# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='videos',
            new_name='video_snippets',
        ),
    ]
