# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='baseproblem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='baseproblem',
            name='picture_1',
        ),
        migrations.RemoveField(
            model_name='baseproblem',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='baseproblem',
            name='picture_3',
        ),
        migrations.RemoveField(
            model_name='baseproblem',
            name='video_snippets',
        ),
        migrations.AddField(
            model_name='problemimage',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
    ]
