# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaimage',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Area'),
        ),
        migrations.AddField(
            model_name='areaimage',
            name='image_map',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Area'),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='done_by',
            field=models.ManyToManyField(blank=True, to='members.Member'),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_problem_set', to='members.Member'),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='See the area map to identify the correct sector name. If the problem crosses multiple sectors, use the sector of the first hold for your left hand.', null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Sector'),
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
        migrations.AddField(
            model_name='problembymember',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='problembymember',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
        migrations.AddField(
            model_name='problemimage',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
        migrations.AddField(
            model_name='problemvideo',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='problemvideo',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
    ]
