# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20161204_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem')),
            ],
        ),
    ]
