# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20161125_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='steepness',
            field=models.CharField(blank=True, choices=[('slab', 'slab'), ('vert', 'vertical'), ('slov', 'slight overhang'), ('over', 'overhang'), ('exov', 'extreme overhang')], max_length=50, null=True),
        ),
    ]
