# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20161128_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='hold_colour',
            new_name='holds',
        ),
    ]
