# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20170119_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaimage',
            name='image_map',
        ),
    ]
