# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_remove_areaimage_image_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaimage',
            name='imagemap',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
