# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_baseproblem_done_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naturalproblem',
            name='rock_type',
        ),
        migrations.AlterField(
            model_name='baseproblem',
            name='done_by',
            field=models.ManyToManyField(blank=True, to='members.Member'),
        ),
    ]
