# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20170108_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area_map_image',
        ),
        migrations.AlterField(
            model_name='artificialproblem',
            name='holds',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='hold colour'),
        ),
    ]
