# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20161205_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemvideo',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
