# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_areaimage_imagemapcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaimage',
            name='imagemapcode',
        ),
    ]
