# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_problemvideo_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemvideo',
            name='embed_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
