# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import members.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20170111_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Area')),
            ],
            bases=(models.Model, members.mixins.PermissionMixin),
        ),
    ]
