# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_remove_areaimage_imagemapcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaimage',
            name='imagemapcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
