# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_remove_problemvideo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemvideo',
            name='embed_code',
            field=models.CharField(default='NONE', max_length=1000),
            preserve_default=False,
        ),
    ]
