# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_auto_20170120_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={},
        ),
    ]
