# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_auto_20170120_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('name',)},
        ),
    ]
