# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_auto_20170126_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemflag',
            name='issue',
            field=models.CharField(choices=[('no longer exists', 'no longer exists'), ('description is inaccurate/unclear', 'description is inaccurate/unclear'), ('loose hold(s)', 'loose hold(s)'), ('other (give a description)', 'other (give a description)')], max_length=100),
        ),
    ]
