# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member'),
        ('guide', '0010_naturalproblem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('natural', 'natural'), ('artificial', 'artificial')], default='artificial', max_length=15),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baseproblem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AlterField(
            model_name='baseproblem',
            name='steepness',
            field=models.CharField(blank=True, choices=[('slab', 'slab'), ('vertical', 'vertical'), ('slightly overhanging', 'slightly overhanging'), ('overhanging', 'overhanging'), ('extremely overhanging', 'extremely overhanging'), ('not applicable', 'not applicable')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='send',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
    ]
