# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_auto_20170120_2344'),
        ('guide', '0011_auto_20170126_1023'),
    ]

    operations = [
    ]
