# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_auto_20161220_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproblem',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
