# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_auto_20161222_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproblem',
            name='steepness',
        ),
    ]
