# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_auto_20170130_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
