# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170126_2122'),
        ('guide', '0015_auto_20170130_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialproblem',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
