# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0015_remove_baseproblem_steepness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Send',
            new_name='MemberByProblem',
        ),
    ]
