# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member'),
        ('guide', '0017_auto_20161227_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproblem',
            name='members',
            field=models.ManyToManyField(through='guide.ProblemByMember', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='baseproblem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_problem_set', to='members.Member'),
        ),
    ]
