# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
