# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='notifications',
            field=models.BooleanField(default=True, help_text='enable/disable email notifications'),
        ),
    ]
