# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20161204_0024'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.BaseProblem'),
        ),
    ]
