# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_videopost_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractpost',
            name='member',
        ),
        migrations.RemoveField(
            model_name='problemcomment',
            name='abstractpost_ptr',
        ),
        migrations.RemoveField(
            model_name='problemcomment',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='abstractpost_ptr',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='problem',
        ),
        migrations.DeleteModel(
            name='AbstractPost',
        ),
        migrations.DeleteModel(
            name='ProblemComment',
        ),
        migrations.DeleteModel(
            name='VideoPost',
        ),
    ]
